services:
    frontend:
        build:
            context: ./frontend
        ports:
            - "5173:80"
        networks:
            - web
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
        ports:
            - "8080:8080"
        networks:
            - web
            - auth

    auth:
        build:
            context: ./auth
        env_file:
            - ./auth/.env
        networks:
            - auth

networks:
    web:
    auth:
        internal: true
