services:
  frontend:
    container_name: front
    build:
      context: ./frontend
    ports:
      - "5173:80"
    networks:
      - forum_project
    depends_on:
      - backend

  backend:
    container_name: back
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - forum_project

  auth_service:
    container_name: auth
    build:
      context: ./auth
    ports:
      - "8081:8081"
    networks:
      - forum_project

networks:
  forum_project:
    name: forum_project
